[window.padding]
x = 10
y = 10

[colors.primary]
  background = "#1d1f21"
  foreground = "#cccccc"

[colors.normal]
  black   = "#282a2e"
  red     = "#bb4040"
  green   = "#8c9440"
  yellow  = "#de935f"
  blue    = "#5f819d"
  magenta = "#85678f"
  cyan    = "#5e8d87"
  white   = "#707880"