[window.padding]
x = 10
y = 10

[font]
  size = 12

# [font.normal]
#   family = "JetBrains Mono NL"

[font.normal]
  family = "terminus"
  style = "Regular"

[colors.primary]
  background = "#212121"
  foreground = "#f6fdd9"

[colors.normal]
  black   = "#484641"
  red     = "#b95f50"
  green   = "#40885f"
  yellow  = "#4a4e77"
  blue    = "#2a8ab6"
  magenta = "#5e49b1"
  cyan    = "#72b8bc"
  white   = "#a2a885"

[colors.bright]
  black   = "#a3ab87"
  red     = "#f67e6a"
  green   = "#51ad79"
  yellow  = "#686ea7"
  blue    = "#39baf5"
  magenta = "#8567fa"
  cyan    = "#9afdfd"
  white   = "#eaf4c1"
