[window.padding]
x = 10
y = 10

[colors.primary]
  background = "${background}"
  foreground = "${foreground}"

[colors.normal]
  black   = "${color0}"
  red     = "${color1}"
  green   = "${color2}"
  yellow  = "${color3}"
  blue    = "${color4}"
  magenta = "${color5}"
  cyan    = "${color6}"
  white   = "${color7}"