#!/usr/bin/env bash
# vim: set filetype=sh :

# 1. Дефолтные значения для аргументов
FILE_PATH="${1}"
PREVIEW_X_COORD="${2:-0}"
PREVIEW_Y_COORD="${3:-0}"
PREVIEW_WIDTH="${4:-10}"
PREVIEW_HEIGHT="${5:-10}"

META_FILE=$(get_preview_meta_file "$FILE_PATH")

get_data_from_meta_file() {
    local key_name=$1
    local data=""

    if [ -f "$META_FILE" ]; then
        data=$(grep "$key_name" "$META_FILE" | awk '{print $2}')
    fi

    echo "$data"
}

HANDLE_DATA=$(get_data_from_meta_file "handle_data")
FILE_TYPE=$(get_data_from_meta_file "file_type")

if [ "$HANDLE_DATA" != "true" ]; then
    remove_image
    exit 1 
fi

if [ "$FILE_TYPE" = "image" ]; then
    # Читаем сохраненный сдвиг из мета-файла
    Y_OFFSET=$(get_data_from_meta_file "y_offset")
    PREVIEW_Y_COORD=$((PREVIEW_Y_COORD + ${Y_OFFSET:-0}))

    show_image "$FILE_PATH" "$PREVIEW_X_COORD" "$PREVIEW_Y_COORD" "$PREVIEW_WIDTH" "$PREVIEW_HEIGHT"
elif [ "$FILE_TYPE" = "pdf" ]; then
    ## todo: Добавить отрисовку
    true
elif [ "$FILE_TYPE" = "book" ]; then
    ## todo: Добавить отрисовку
    true
else
    remove_image
fi 

