# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Update .Xresources

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3


# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Icons in workspace names :3
exec_always --no-startup-id workstyle &> /tmp/workstyle.log

# wallpaper
exec --no-startup-id nitrogen --restore

# Compositor
exec --no-startup-id picom --config ~/.config/picom/picom.conf

# Update app configurations based on .Xresources file
# exec_always --no-startup-id ~/.config/i3/scripts/update-configs-by-xres.sh

# Select pointer corsor by default
exec --no-startup-id sh -c 'sleep 1 && xsetroot -cursor_name left_ptr'

# clipboard manager
exec --no-startup-id clipmenud

# Alt-tab util
exec_always --no-startup-id $HOME/.config/i3/scripts/run-alt-tab.sh

# Resize mode script 
exec_always --no-startup-id python3 $HOME/.config/i3/scripts/watch_resize_mode.py

# Keyboard sound
# exec --no-startup-id mechvibes --inprocess-gpu
# Если запускается как-то не правильно:
exec --no-startup-id mechvibes --in-process-gpu & disown

# Прокси-фикс для Telegram
exec --no-startup-id tg-ws-proxy
