for_window [class="floating_shell"] floating enable

# Runescape RSPS client Alora
for_window [class="com-alora-updater-Splash"] floating enable
for_window [class="net-runelite-client-RuneLite"] floating enable
for_window [class="com-alora-Alora"] floating enable
