[[bookmark]]
key = "g"
path = "/home/nekzie/.config/ghostty"

[[bookmark]]
key = "w"
path = "/home/nekzie/Documents/projects/code"

[[bookmark]]
key = "b"
path = "/home/nekzie/.local/bin"

[[bookmark]]
key = "c"
path = "/home/nekzie/Documents/projects/code/i3-desk-wizard/config"
