
# базовые переменные
$CONF="$HOME/.config"

files=(
  "Xresources:  $HOME/.Xresources"
  "polybar:     $CONF/polybar/config.ini"
  "nitrogen:    $CONF/nitrogen/config.ini"
  "i3:          $CONF/i3/config.d/appearance.conf"


)

